[package]
name = "mandelbrot-svg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.24.5"
chrono="0.4.23"

[profile.dev]
opt-level=3

[profile.release]
opt-level=3
